version: "3"

services: 
    db:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=postgres
    dj:
        container_name: dj
        build: .
        command: python manage.py runserver 0.0.0.0:80
        # working_dir: /code
        volumes: 
            - ./django:/code
        ports: 
            - "80:80"
        depends_on: 
            - db